#!/bin/bash

if [ -L "$0" ]; then
    script_dir=$(cd "$(dirname "$(readlink "$0")")" && pwd)
else
    script_dir=$(cd "$(dirname "$0")" && pwd)
fi

FLAVOR="$1"
test -z "$FLAVOR" && {
    echo "usage: $0 <FLAVOR> <FULL_TAG>"
    exit 1
}

TAG="$2"
test -z "$TAG" && {
    echo "usage: $0 <FLAVOR> <FULL_TAG>"
    exit 1
}

set -ex

cp "${script_dir}/../all/Dockerfile" "${script_dir}/../${FLAVOR}/Dockerfile"

docker build --tag "$TAG" \
    --label org.opencontainers.image.created="$(date --rfc-3339=seconds)" \
    --label org.opencontainers.image.url="https://github.com/${GITHUB_REPOSITORY}" \
    --label org.opencontainers.image.documentation="https://github.com/octodns/octodns#readme" \
    --label org.opencontainers.image.source="https://github.com/${GITHUB_REPOSITORY}" \
    --label org.opencontainers.image.revision="$GITHUB_SHA" \
    --label org.opencontainers.image.licenses=MIT \
    "$FLAVOR"
