#!/bin/bash

if [ -L "$0" ]; then
    script_dir=$(cd "$(dirname "$(readlink "$0")")" && pwd)
else
    script_dir=$(cd "$(dirname "$0")" && pwd)
fi

FLAVOR="$1"
test -z "$FLAVOR" && {
    echo "usage: $0 <FLAVOR> <FULL_TAG>"
    exit 1
}

TAG="$2"
test -z "$TAG" && {
    echo "usage: $0 <FLAVOR> <FULL_TAG>"
    exit 1
}
FULL_TAG="${TAG}:$(date +"%Y.%m")"

set -ex

"${script_dir}/cibuild" "$FLAVOR" "$FULL_TAG"
docker push "$FULL_TAG"
docker tag "$FULL_TAG" "${TAG}:latest"
docker push "${TAG}:latest"
